@startuml Smarthome-component-sensors-manage
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml
LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

title Component diagram for sensors-manage-service container

ContainerDb(telemetry_cache, "Telemetry cache", "Redis", "Телеметрия")
ContainerDb(telemetry_history, "Telemetry history", "S3", "Телеметрия (теплые данные)")

System_Ext(sensor, "Умные устройства")

ContainerQueue(smarthome_mq, "Message Queue", "kafka")

Container_Boundary(sensors_gw_service, "Sensors manage service") {
    Component(sensors_gw,"Sensors gateway", "Component", "Компонент внешних соединений с устройствами")
    Component(sensors_service,"Sensors service", "Service", "Сервис проверки устройств")
    Component(telemetry_service,"Telemetry component", "Component", "Компонент обработки телеметрии")
    Component(command_service,"Command component", "Component", "Компонент обработки команд")
}
Rel_U(command_service, smarthome_mq, "read, write", "JSON Binary/TCP")

Rel(command_service, sensors_gw, "publish task")
Rel(sensors_gw, telemetry_service, "publish data")
Rel(command_service, sensors_service, "use")

Rel(telemetry_service, sensors_service, "use")
Rel_U(telemetry_service, smarthome_mq, "write", "JSON Binary/TCP")
Rel(telemetry_service, telemetry_cache, "write", "TCP?")
Rel(telemetry_service, telemetry_history, "write", "HTTPS")

Rel(sensors_service, telemetry_cache, "read", "TCP")

Rel_U(sensor, sensors_gw, "use", "JSON Binary/HTTPS, other internet protocols")
Rel_D(sensors_gw, sensor, "use", "JSON Binary/HTTPS, other internet protocols")

@enduml