@startuml Smarthome-component-partner

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for partner-service container

Container(admin_web_app, "Web Application", "ReactJS", "Сайт для администрирования экосистемы")
ContainerDb(partner_service_db, "Partner-db", "Postgresql", "Каталог доступных устройств и их команд")
Container(devices_manage_service, "Devices manage service", "Golang", "Сервис позволяет зарегистрировать устройство, локацию, получить список устройств и их состояние")

Container_Boundary(partner_service, "Partner service container") {
    Component(auth_check, "Auth check","Component", "Проверяет доступ по токену")
    Component(devices_catalog_controller, "Devices catalog controller", "MVC Rest Controller", "API для управления каталогом устройств и их команд, партнеров")

    Component(devices_catalog_service, "Devices catalog component", "Component", "Компонент для управления каталогом")
}
Rel(admin_web_app, devices_catalog_controller, "Use", "JSON/HTTPS")
Rel(devices_manage_service, devices_catalog_controller, "Use", "JSON/HTTPS")

Rel_L(devices_catalog_controller, auth_check, "use")
Rel_R(devices_catalog_controller, devices_catalog_service, "use")

Rel(devices_catalog_service, partner_service_db, "read, write", "JDBC")

@enduml