@startuml
entity User {
    id
    name
    email
    is_blocked
}

entity Device {
    id
    name
    status
    serial_number
}

enum Device_Classification_Enum {
    code
    name
}

entity Device_Type {
    id
    name
    unit
    is_supported
    +JSON connection_data
    +JSON avalable_commands 
}

entity Partner {
    id
    name
    inn
}


entity House {
    id
    name
}

entity Location {
    id
    name
}

entity Telemetry {
    date
    value
    unit
}

entity Scenario {
    scenario_data
}

User "1" -- "0..*" House: has
House "1" -- "1..*" Location: includes
Location "1" -- "0..*" Device: includes
Device "1" -- "0..*" Telemetry: has
Device "0..*" -- "1" Device_Type: has
Scenario "1..*" -- "1..*" Device: includes
Device_Type "0..*" -- "1" Partner: developed by
Device_Type "0..*" -- "1" Device_Classification_Enum: classified as

@enduml