@startuml Smarthome-Context-Map
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title System Landscape diagram for Warm House TO-BE

Person(user, "Клиент", "Клиент экосистемы умного дома")
Person(admin, "Администратор", "Администратор экосистемы")

Enterprise_Boundary(c0, "Система управления умным домом") {
    Boundary(smart_home_manage_b, $type="Домен", "Домен управления умным домом") {
        System(smart_home_manage, "Система управления устройствами")
        Boundary(sensors_manage_b, $type="поддомен", "Поддомен управления устройствами"){
            System(sensors_manage_с, "Контекст управление устройствами")
        }
        Boundary(sensors_monitoring_b, $type="поддомен", "Поддомен взаимодействие с устройствами"){
            System(sensors_monitoring_c, "Контекст получение и обработка телеметрии с устройств")
            System(sensors_command_с, "Контекст отправка команд на устройство")
        }
    }
    System_Boundary(scenario_b, "Домен автоматизации сценариев") {
        Boundary(scenario_manage_b, $type="поддомен", "Поддомен управление сценариями"){
            System(scenario_manage_c, "Контекст создание и управление сценариями умного дома")
            System(scenario_event_monitoring_c, "Контекст отслеживание событий и отправка команд на устройства")
        }
    }

    System_Boundary(system_manage_b, "Домен управления экосистемой") {
        Boundary(partners_manage_b, $type="поддомен", "Поддомен управление парнерами"){
            System(partners_manage_c, "Контекст управление доступными устройствами партнеров и командами ")
        }
        Boundary(user_manage_b, $type="поддомен","Поддомен управление пользователями"){
            System(user_manage_c, "Контекст авторизация пользователя")
        }

    }
    System_Ext(sensor, "Умные устройства")
}

Rel(user,smart_home_manage, "Управляет устройствами")
Rel(user, user_manage_c, "Авторизуется и регистрируется")

Rel(smart_home_manage, sensors_manage_с, " Получает, регистрирует устройства via")
Rel(smart_home_manage, sensors_monitoring_c, "Получает телеметрию via")
Rel(smart_home_manage, sensors_command_с, "Отправляет команды на устройства via")

Rel(sensors_manage_с, partners_manage_c, " Получает доступные устройства via")
Rel(sensors_manage_с, sensors_monitoring_c, "Сообщает о новых устройствах")

Rel(sensors_monitoring_c, sensor, "Получает телеметрию")
' Rel(sensors_monitoring_c, scenario_event_monitoring_c, "Передает телеметрию для сценариев")

Rel(sensors_command_с, sensor, "Отправляет команды")
Rel(sensors_command_с, partners_manage_c, "Проверяет доступные команды")

Rel(user,scenario_manage_c, "Управляет сценариями")
' систем управления сценариями получает статус исполнения сценариев

Rel(scenario_manage_c,scenario_event_monitoring_c, "Сообщает об изменении сценария")

Rel(scenario_event_monitoring_c, sensors_monitoring_c, "Получает телеметрию для сценариев")
' или напрямую с датчика? 
Rel(scenario_event_monitoring_c, sensors_command_с, "Отправляет команды")
Rel(scenario_event_monitoring_c, scenario_manage_c, "Сообщает о статусе исполнения сценария")

Rel(admin, partners_manage_c, "Управляет доступными устройствами,партнерами, командами")
Rel(admin, user_manage_c, "Управляет доступом клиентов")
Rel(user, user_manage_c, "Регистрируется, получает доступы")
@enduml