@startuml Smarthome-component-device-manage 
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for device-manage-service container

Container(admin_web_app, "Web Application", "ReactJS", "Сайт для администрирования экосистемы")
Container(mobile_app, "Mobile App", "C#, Xamarin", "Приложение для управления умным домом для клиента")

Container(partner_service, "Partner service", "Golang", "Сервис управления доступными устройствами партнеров и их командами")
ContainerDb(device_manage_service_db, "device-manage-db", "Postgresql", "Зарегистрированные устройства, привязка к локации, каталог локаций")
ContainerDb(telemetry_cache, "Telemetry cache", "Redis", "Телеметрия")
ContainerDb(telemetry_history, "Telemetry history", "S3", "Телеметрия (теплые данные)")

ContainerQueue(smarthome_mq, "Message Queue", "kafka")

Container_Boundary(device_manage_service, "device manage container") {
    Component(auth_check, "Auth check","Component", "Проверяет доступ по токену")
    Component(device_controller, "device management controller", "MVC Rest Controller", "API для взаимодействия с устройствами")

    Component(device_service, "device component", "Компонент", "Компонент управления устройствами")
    Component(location_service, "Location component", "Компонент", "Компонент управления локациями")
    Component(telemetry_service, "Telemetry component", "Компонент", "Компонент получения телеметрии")
    Component(command_service, "Command component", "Компонент", "Компонент отправки команд на устройство")
    Component(partner_component, "Partner component", "Компонент", "Компонент валидации устройств и команд")

}
Rel(mobile_app, device_controller, "Use", "WebSockets, HTTPS")
Rel(admin_web_app, device_controller, "Use", "HTTPS")


Rel(device_controller, device_service, "use")
Rel(device_controller, location_service, "use")
Rel(device_controller, telemetry_service, "use")
Rel(device_controller, command_service, "use")
Rel(device_controller, auth_check, "use")
Rel(device_controller, partner_component, "use")

Rel(partner_component, partner_service, "use", "JSON/HTTPS")

Rel(device_service, device_manage_service_db, "read, write to", "JDBC")
Rel(device_service, telemetry_cache, "write to", "TCP")

Rel(location_service, device_manage_service_db, "read, write to", "JDBC")
Rel(telemetry_service, telemetry_cache, "reads from", "TCP")
Rel(telemetry_service, telemetry_history, "reads from", "JSON/HTTPS")
Rel(command_service, smarthome_mq, "sends commands", "JSON/TCP")

@enduml