name: PlantUML Diagrams

on: [push]

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Automated diagram generation')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Install PlantUML
        run: sudo apt-get install plantuml

      - name: Generate Diagrams
        run: |
          plantuml schemas/context/*.puml
          plantuml schemas/container/*.puml
          plantuml schemas/component/*.puml
          plantuml schemas/code/*.puml

      - name: Commit Diagrams
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add schemas/**/*.png
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated diagram generation"
          git push
          # git commit -m "Automated diagram generation"
          # git push origin main
        if: success()
